require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CalculatedGamePlayerStatisticsController do

  # This should return the minimal set of attributes required to create a valid
  # CalculatedGamePlayerStatistic. As you add validations to CalculatedGamePlayerStatistic, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CalculatedGamePlayerStatisticsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all calculated_game_player_statistics as @calculated_game_player_statistics" do
      calculated_game_player_statistic = CalculatedGamePlayerStatistic.create! valid_attributes
      get :index, {}, valid_session
      assigns(:calculated_game_player_statistics).should eq([calculated_game_player_statistic])
    end
  end

  describe "GET show" do
    it "assigns the requested calculated_game_player_statistic as @calculated_game_player_statistic" do
      calculated_game_player_statistic = CalculatedGamePlayerStatistic.create! valid_attributes
      get :show, {:id => calculated_game_player_statistic.to_param}, valid_session
      assigns(:calculated_game_player_statistic).should eq(calculated_game_player_statistic)
    end
  end

  describe "GET new" do
    it "assigns a new calculated_game_player_statistic as @calculated_game_player_statistic" do
      get :new, {}, valid_session
      assigns(:calculated_game_player_statistic).should be_a_new(CalculatedGamePlayerStatistic)
    end
  end

  describe "GET edit" do
    it "assigns the requested calculated_game_player_statistic as @calculated_game_player_statistic" do
      calculated_game_player_statistic = CalculatedGamePlayerStatistic.create! valid_attributes
      get :edit, {:id => calculated_game_player_statistic.to_param}, valid_session
      assigns(:calculated_game_player_statistic).should eq(calculated_game_player_statistic)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CalculatedGamePlayerStatistic" do
        expect {
          post :create, {:calculated_game_player_statistic => valid_attributes}, valid_session
        }.to change(CalculatedGamePlayerStatistic, :count).by(1)
      end

      it "assigns a newly created calculated_game_player_statistic as @calculated_game_player_statistic" do
        post :create, {:calculated_game_player_statistic => valid_attributes}, valid_session
        assigns(:calculated_game_player_statistic).should be_a(CalculatedGamePlayerStatistic)
        assigns(:calculated_game_player_statistic).should be_persisted
      end

      it "redirects to the created calculated_game_player_statistic" do
        post :create, {:calculated_game_player_statistic => valid_attributes}, valid_session
        response.should redirect_to(CalculatedGamePlayerStatistic.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved calculated_game_player_statistic as @calculated_game_player_statistic" do
        # Trigger the behavior that occurs when invalid params are submitted
        CalculatedGamePlayerStatistic.any_instance.stub(:save).and_return(false)
        post :create, {:calculated_game_player_statistic => {}}, valid_session
        assigns(:calculated_game_player_statistic).should be_a_new(CalculatedGamePlayerStatistic)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CalculatedGamePlayerStatistic.any_instance.stub(:save).and_return(false)
        post :create, {:calculated_game_player_statistic => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested calculated_game_player_statistic" do
        calculated_game_player_statistic = CalculatedGamePlayerStatistic.create! valid_attributes
        # Assuming there are no other calculated_game_player_statistics in the database, this
        # specifies that the CalculatedGamePlayerStatistic created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CalculatedGamePlayerStatistic.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => calculated_game_player_statistic.to_param, :calculated_game_player_statistic => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested calculated_game_player_statistic as @calculated_game_player_statistic" do
        calculated_game_player_statistic = CalculatedGamePlayerStatistic.create! valid_attributes
        put :update, {:id => calculated_game_player_statistic.to_param, :calculated_game_player_statistic => valid_attributes}, valid_session
        assigns(:calculated_game_player_statistic).should eq(calculated_game_player_statistic)
      end

      it "redirects to the calculated_game_player_statistic" do
        calculated_game_player_statistic = CalculatedGamePlayerStatistic.create! valid_attributes
        put :update, {:id => calculated_game_player_statistic.to_param, :calculated_game_player_statistic => valid_attributes}, valid_session
        response.should redirect_to(calculated_game_player_statistic)
      end
    end

    describe "with invalid params" do
      it "assigns the calculated_game_player_statistic as @calculated_game_player_statistic" do
        calculated_game_player_statistic = CalculatedGamePlayerStatistic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CalculatedGamePlayerStatistic.any_instance.stub(:save).and_return(false)
        put :update, {:id => calculated_game_player_statistic.to_param, :calculated_game_player_statistic => {}}, valid_session
        assigns(:calculated_game_player_statistic).should eq(calculated_game_player_statistic)
      end

      it "re-renders the 'edit' template" do
        calculated_game_player_statistic = CalculatedGamePlayerStatistic.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CalculatedGamePlayerStatistic.any_instance.stub(:save).and_return(false)
        put :update, {:id => calculated_game_player_statistic.to_param, :calculated_game_player_statistic => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested calculated_game_player_statistic" do
      calculated_game_player_statistic = CalculatedGamePlayerStatistic.create! valid_attributes
      expect {
        delete :destroy, {:id => calculated_game_player_statistic.to_param}, valid_session
      }.to change(CalculatedGamePlayerStatistic, :count).by(-1)
    end

    it "redirects to the calculated_game_player_statistics list" do
      calculated_game_player_statistic = CalculatedGamePlayerStatistic.create! valid_attributes
      delete :destroy, {:id => calculated_game_player_statistic.to_param}, valid_session
      response.should redirect_to(calculated_game_player_statistics_url)
    end
  end

end
